for (var i = 0; i < 10; i++){
    console.log(i)
}
console.log('i =', i)//valor que sai do laço. E como var nao fica definido apenas dentro da função, nao gera erro ao executar
